#!/usr/bin/python
# -*- coding: utf-8 -*-
# gd 20130804
"""
correct some part of latex file generated by pandoc to clean up the latex file

"""


import argparse
import re
import subprocess
import shutil
import os

def print_r(v):
    return '%s = %r %s' % (v, v, type(v))

	
def includegraphics2figure(args=None):
	"""
		Subsitute all includegraphics with the \bgefin{figure} part
	"""
	
	shutil.move(args.input,args.input+'.tmp')
	out = open(args.input,'w',encoding='utf8')
	
	with open(args.input+'.tmp','r',encoding='utf8') as f:
		for line in f:
			espressione = '\includegraphics\{Images\/index'
			if not re.search(espressione, line,re.I):
				out.write(line)
			else: 
				(sl,sr) = line.split('-')
				(img_number,srr) = sr.split('.')
				new_string = """
\\begin{figure}[h!]
	\centering
	\includegraphics[width=0.75\\textwidth]{Images/index-###NUM###.png}
	\caption{}
	\label{fig_x###NUM###}
\end{figure}

"""
				final_string = new_string.replace("###NUM###",img_number)
				out.write(final_string)
				
	os.remove(args.input+'.tmp')
			

def run(args=None):

	shutil.copy(args.input,args.input+'.bak')
	includegraphics2figure(args)
			
def main():
	
	parser = argparse.ArgumentParser(description='Demo of argparse')
	parser.add_argument("input", help='directory in cui ci sono i film da analizzare')
#	parser.add_argument('-o','--output',help='Output file name', default='output.tex')
	args = parser.parse_args()

	run(args)

if __name__ == '__main__':
    main()
    


